# https://docs.github.com/ja/actions/guides/building-and-testing-java-with-gradle
name: Java CI
on: [push]
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 21 ]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
    - name: Build with Gradle
      run: ./gradlew executableJar --no-daemon
    - name: Show help
      run: ./gradlew run --args='--help'
